#include <stdio.h>
#include <string.h>
#include <allegro5/allegro5.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_image.h>
#include <allegro5/allegro_native_dialog.h>
#include <matrix.h>
#include <structs.h>
#include <signal.h>

int __algorithm;
int __numberProcess;
int __PPID;

typedef martian *tpuntero; //Puntero al tipo de dato martian para no utilizar punteros de punteros

int parameterAlgorithm(int argc, char *argv[])
{
    if (argc != 2)
    {
        printf("Warning!, only one input parameter must be provided\n");
        return 0;
    }

    if (!strcmp(argv[1], "RM"))
    {
        __algorithm = 0;
        return 1;
    }
    else if (!strcmp(argv[1], "EDF"))
    {
        __algorithm = 1;
        return 1;
    }
    else
    {
        printf("Algorithm error\n");
        return 0;
    }
}

/* martian *_martian = malloc(sizeof(martian)); // Reserva el espacio de memoria para el marciano */
/* Lista */

void insertarEnLista(tpuntero *node_martian, int energy_, int period_)
{
    tpuntero new_martian;                  //Creamos un nuevo nodo
    new_martian = malloc(sizeof(martian)); //Utilizamos malloc para reservar memoria para ese nodo
    new_martian->energy = energy_;         //Le asignamos el valor ingresado por pantalla a ese nodo
    new_martian->period = period_;         //Le asignamos el valor ingresado por pantalla a ese nodo
    new_martian->next_martian = *node_martian;      //Le asignamos al siguiente el valor de cabeza
    *node_martian = new_martian;           //Cabeza pasa a ser el ultimo nodo agregado
}

void imprimirLista(tpuntero node)
{
    while (node != NULL)
    {                                                                    //Mientras node no sea NULL
        printf("\nEnergy: %f  -  Period: %f\n", node->energy, node->period); //Imprimimos el valor del nodo
        node = node->next_martian;                                                //Pasamos al siguiente nodo
    }
}

void borrarLista(tpuntero *node_martian)
{
    tpuntero node_temp; //Puntero auxiliar para eliminar correctamente la lista

    while (*node_martian != NULL)
    {                                         //Mientras node_martian no sea NULL
        node_temp = *node_martian;               //Actual toma el valor de node_martian
        *node_martian = (*node_martian)->next_martian; //Cabeza avanza 1 posicion en la lista
        free(node_temp);                         //Se libera la memoria de la posicion de Actual (el primer nodo), y node_martian queda apuntando al que ahora es el primero
    }
}
/* -------------- MAIN ------------- */
int main(int argc, char *argv[])
{

    tpuntero node_martian; //Indica la node_martian de la lista enlazada, si la perdemos no podremos acceder a la lista
    node_martian = NULL;   //Se inicializa la node_martian como NULL ya que no hay ningun nodo cargado en la lista

    if (!parameterAlgorithm(argc, argv))
    {
        return 0;
    }

    if (!al_init())
    {
        printf("couldn't initialize allegro\n");
        return 1;
    }

    if (!al_install_keyboard())
    {
        printf("couldn't initialize keyboard\n");
        return 1;
    }

    if (!al_init_image_addon())
    {
        printf("couldn't initialize image addon\n");
        return 1;
    }

    ALLEGRO_TIMER *timer = al_create_timer(1.0 / 30.0);
    if (!timer)
    {
        printf("couldn't initialize timer\n");
        return 1;
    }

    ALLEGRO_EVENT_QUEUE *queue = al_create_event_queue();
    if (!queue)
    {
        printf("couldn't initialize queue\n");
        return 1;
    }

    ALLEGRO_DISPLAY *disp = al_create_display(608, 608);
    if (!disp)
    {
        printf("couldn't initialize display\n");
        return 1;
    }

    ALLEGRO_FONT *font = al_create_builtin_font();
    if (!font)
    {
        printf("couldn't initialize font\n");
        return 1;
    }

    ALLEGRO_BITMAP *alien = al_load_bitmap("../src/alien.png");
    ALLEGRO_BITMAP *maze = al_load_bitmap("../src/maze.png");

    if (!alien || !maze)
    {
        puts("couldn't load alien\n");
        return 1;
    }

    al_register_event_source(queue, al_get_keyboard_event_source());
    al_register_event_source(queue, al_get_display_event_source(disp));
    al_register_event_source(queue, al_get_timer_event_source(timer));

    bool done = false;
    bool redraw = true;
    ALLEGRO_EVENT event;

    int x_alien = 0;

    int new_martian = 0;
    int energy = 0;
    int period = 0;

    /*     int c = al_show_native_message_box(
        disp,
        "Fin de Partida",
        "Quieres reiniciar",
        "Si as'i lo dIf you click yes then you are confirming that \"Yes\""
        "is your response to the query which you have"
        "generated by the action you took to open this"
        "message box.",
        NULL,
        ALLEGRO_MESSAGEBOX_OK_CANCEL);
    printf("%d\n", c); */

    al_start_timer(timer);
    while (1)
    {
        al_wait_for_event(queue, &event);

        switch (event.type)
        {
        case ALLEGRO_EVENT_TIMER:

            // game logic goes here.
            if (x_alien >= 0 && x_alien < 608)
            {
                x_alien++;
            }
            else
            {
                x_alien = 0;
            }

            redraw = true;
            break;

        case ALLEGRO_EVENT_KEY_DOWN:
            if (event.keyboard.keycode == ALLEGRO_KEY_X)
            {
                done = true;
            }
            if (event.keyboard.keycode == ALLEGRO_KEY_L)
            {
                printf("\nSe imprime la lista cargada: ");
                imprimirLista(node_martian);
            }
            if (event.keyboard.keycode == ALLEGRO_KEY_ENTER)
            {
                if (new_martian == 1) // Deshabilita la creacion de marcianos
                {

                    if (energy != 0 && period != 0)
                    {
                        /* Create threat */
                        printf("Create Hilo con data...\n");
                        insertarEnLista(&node_martian, energy, period);
                    }
                    else
                    {
                        /* No hacer nada, */
                        printf("Sin data...\n");
                    }

                    new_martian = 0;
                    energy = 0;
                    period = 0;
                }
                else // Habilita la creacion de marcianos
                {
                    new_martian = 1;
                }
            }
            if (new_martian == 1)
            {
                if (event.keyboard.keycode == ALLEGRO_KEY_E)
                {
                    energy++;
                }
                else if (event.keyboard.keycode == ALLEGRO_KEY_P)
                {
                    period++;
                }
            }

            break;
        case ALLEGRO_EVENT_DISPLAY_CLOSE:
            done = true;
            break;
        }

        if (done)
        {
            printf("\nSe borra la lista cargada\n");
            borrarLista(&node_martian);
            break;
        }

        if (redraw && al_is_event_queue_empty(queue))
        {
            al_clear_to_color(al_map_rgb(255, 255, 255));

            al_draw_bitmap(maze, 0, 0, 0);

            al_draw_bitmap(alien, x_alien + 50, 224, 0);
            al_draw_bitmap(alien, x_alien + 100, 224, 0);
            al_draw_bitmap(alien, x_alien + 150, 224, 0);
            al_draw_bitmap(alien, x_alien + 200, 224, 0);
            al_draw_bitmap(alien, x_alien + 250, 224, 0);

            al_draw_text(font, al_map_rgb(178, 178, 178), 460, 10, 0, "ENERGY: ");
            al_draw_text(font, al_map_rgb(178, 178, 178), 520, 10, 0, ">>>>>>>>>>");

            if (new_martian)
            {
                char *str_energy;
                asprintf(&str_energy, "%i", energy);
                al_draw_text(font, al_map_rgb(178, 120, 211), 10, 10, 0, "Energy: ");
                al_draw_text(font, al_map_rgb(255, 255, 255), 70, 10, 0, str_energy);
                free(str_energy);

                char *str_period;
                asprintf(&str_period, "%i", period);
                al_draw_text(font, al_map_rgb(178, 120, 211), 108, 10, 0, "Period: ");
                al_draw_text(font, al_map_rgb(255, 255, 255), 170, 10, 0, str_period);
                free(str_period);

                /* Meter Marciano a lista */
            }

            al_flip_display();
            redraw = false;
        }
    }

    al_destroy_bitmap(alien);
    al_destroy_bitmap(maze);

    al_destroy_font(font);
    al_destroy_display(disp);
    al_destroy_timer(timer);
    al_destroy_event_queue(queue);

    return 0;
}